// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 * SessionInfo 会话元数据（索引中存储）
 */
export interface SessionInfo {
  /**
   * 会话 ID（文件名中的 UUID）
   */
  id: string;
  /**
   * 项目真实路径（从 cwd 字段获取）
   */
  project: string;
  /**
   * 会话开始时间
   */
  startTime: string;
  /**
   * 会话最后活动时间
   */
  lastTime: string;
  /**
   * 消息数量（user + assistant）
   */
  messageCount: number /* int */;
  /**
   * 文件大小（字节）
   */
  fileSize: number /* int64 */;
}
/**
 * SearchRequest 搜索请求参数
 */
export interface SearchRequest {
  q: string;
  project?: string;
  offset: number /* int */;
  limit: number /* int */;
}
/**
 * SearchResult 搜索结果
 */
export interface SearchResult {
  results: SearchHit[];
  total: number /* int */;
  hasMore: boolean;
  queryTimeMs: number /* int64 */;
}
/**
 * SearchHit 单条搜索命中
 */
export interface SearchHit {
  sessionId: string;
  messageUuid: string;
  project: string;
  role: string;
  timestamp: string;
  snippet: string;
  highlights: Highlight[];
}
/**
 * ContextResponse 上下文消息响应
 */
export interface ContextResponse {
  messages: Message[];
  hitIndex: number /* int */;
}
/**
 * StatsResponse 统计信息响应
 */
export interface StatsResponse {
  sessions: number /* int */;
  totalSize: number /* int64 */;
}
/**
 * Highlight 高亮位置
 */
export interface Highlight {
  start: number /* int */;
  end: number /* int */;
}
/**
 * Message 单条消息
 */
export interface Message {
  uuid: string;
  role: string;
  text: string;
  timestamp: string;
}
